---
header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage{booktabs} 
    - \usepackage{tabularx}
output:   
  bookdown::pdf_document2:
  fig_caption: true
  fontsize: 10.5pt
---

```{r Load-pakker, include=FALSE}
library(dplyr) # Wrangling
library(tidyr) # Wranling
library(ggplot2) # Plot
library(ggpubr) #Flere plots på samme side
library(viridis)
library(emmeans)
library(broom)
library(stargazer)
```

## Signifikanstest af kendskab med og uden parti
```{r Indlaes-survey-data-kendskab, include=FALSE, echo=FALSE}
eksperiment_df<-readRDS(file="/Users/annesofieevert/Google_Drive_evert.klint.2019@gmail.com/04_Data/02_Estimation/02_Data/survey_df_clean.Rds")
```

```{r formand-eller-ej, include=FALSE, echo=FALSE}
#Laver en variabel for om man i surveyet har fået formand fra parti man ville stemme på (1) eller en tilfældigt anden (0)
eksperiment_df$egen_formand_dik <- 99
eksperiment_df$egen_formand_dik[is.na(eksperiment_df$udd_egen_formand) == FALSE & is.na(eksperiment_df$udd_anden_formand) == TRUE] <- 1
eksperiment_df$egen_formand_dik[is.na(eksperiment_df$udd_egen_formand) == TRUE & is.na(eksperiment_df$udd_anden_formand) == FALSE] <- 0

#Hvis man ikke har fået egen formand eller anden formand, så har man ikke angivet et parti man ville stemme på ved valg imorgen, og vi sætter derfor resten til NA.
eksperiment_df <- eksperiment_df %>%
  filter(egen_formand_dik==1|egen_formand_dik==0)

#Der er i alt 767 respondenter, der har fået spørgsmål omkring formændenes uddannelse og erhvervserfaring
sum(table(eksperiment_df$egen_formand_dik))

#363 har fået egen kandidat, og 404 har fået tilfældig anden
table(eksperiment_df$egen_formand_dik)

# Hvilken formand har respondenten set
eksperiment_df$formand_set <- 99
eksperiment_df$formand_set[eksperiment_df$egen_formand_dik==1]<-eksperiment_df$egen_formand[eksperiment_df$egen_formand_dik==1]
eksperiment_df$formand_set[eksperiment_df$egen_formand_dik==0]<-eksperiment_df$egen_formand[eksperiment_df$egen_formand_dik==0]

eksperiment_df$formand_set <- factor(eksperiment_df$formand_set, 
                                     labels=levels(eksperiment_df$egen_formand))
```

```{r ved-ikke-udd-wrangling, echo=FALSE, include=FALSE, out.width='70%', fig.align='center'}
#Tjekker data
table(eksperiment_df$udd_egen_formand)
table(eksperiment_df$udd_anden_formand)

#Laver variabel der viser, om man har svaret ved ikke (1) eller givet et bud (0)
eksperiment_df$ved_ikke_udd <- 99
eksperiment_df$ved_ikke_udd[eksperiment_df$udd_egen_formand=="Ved ikke"] <- 1
eksperiment_df$ved_ikke_udd[eksperiment_df$udd_anden_formand=="Ved ikke"] <- 1

#Dem som hverken har fået egen formand eller tilfældig anden formand gøres til NA
eksperiment_df$ved_ikke_udd[is.na(eksperiment_df$udd_egen_formand) == TRUE & is.na(eksperiment_df$udd_anden_formand) == TRUE] <- NA

#De resterende, som ikke har svaret ved ikke og som ikke er NA, har angivet et bud.
eksperiment_df$ved_ikke_udd[eksperiment_df$ved_ikke_udd==99] <- 0
table(eksperiment_df$ved_ikke_udd)
```

```{r logit-udd-ved-ikke, fig.cap="Kendskab til partiformændenes uddannelse", echo=FALSE, include=FALSE}
# FORMÆNDENES UDDANNELSE SAMLET
#Først uden parti
sig_ved_ikke_udd_logit<-glm(formula = as.numeric(ved_ikke_udd) ~ as.factor(egen_formand_dik), 
                            family = binomial(link = "logit"), 
                            data = eksperiment_df)

#Så med parti
sig_ved_ikke_udd_logit_parti<-glm(formula = as.numeric(ved_ikke_udd) ~ as.factor(egen_formand_dik) + formand_set, 
                            family = binomial(link = "logit"), 
                            data = eksperiment_df)
```

```{r stargaz-logitudd-ved-ikke, results='asis', message=F, warning=FALSE, echo=FALSE, eval=TRUE}
stargazer(sig_ved_ikke_udd_logit, sig_ved_ikke_udd_logit_parti, title="Ved ikke til formændenes uddannelse", align=TRUE, type='latex',header=FALSE)
```

```{r udd-wrangling-1, echo=FALSE, include=FALSE}
#Undersøger variablene
unique(eksperiment_df$udd_egen_formand)
unique(eksperiment_df$egen_formand)

table(eksperiment_df$egen_formand)

#Koder dikotom variabel for, om respondenterne har gættet rigtigt på uddannelse
eksperiment_df$formand_dik_udd <- 99

#Anders Samuelsen
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Anders Samuelsen (Liberal Alliance)" & eksperiment_df$udd_egen_formand =="Kandidatuddannelse i Statskundskab"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Anders Samuelsen (Liberal Alliance)" & eksperiment_df$udd_anden_formand =="Kandidatuddannelse i Statskundskab"] <- 1

#Kristian Thulesen Dahl
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Kristian Thulesen Dahl (Dansk Folkeparti)" & eksperiment_df$udd_egen_formand =="Kandidatuddannelse i Erhvervsøkonomi"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Kristian Thulesen Dahl (Dansk Folkeparti)" & eksperiment_df$udd_anden_formand =="Kandidatuddannelse i Erhvervsøkonomi"] <- 1

#Lars Løkke Ramussen
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Lars Løkke Rasmussen (Venstre)" & eksperiment_df$udd_egen_formand =="Kandidatuddannelse i Jura"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Lars Løkke Rasmussen (Venstre)" & eksperiment_df$udd_anden_formand =="Kandidatuddannelse i Jura"] <- 1

#Mette Frederiksen
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Mette Frederiksen (Socialdemokratiet)" & eksperiment_df$udd_egen_formand =="Masteruddannelse i Afrikastudier"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Mette Frederiksen (Socialdemokratiet)" & eksperiment_df$udd_anden_formand =="Masteruddannelse i Afrikastudier"] <- 1

#Morten Østergaard
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Morten Østergaard (Radikale Venstre)" & eksperiment_df$udd_egen_formand =="Kandidatuddannelse i Statskundskab"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Morten Østergaard (Radikale Venstre)" & eksperiment_df$udd_anden_formand =="Kandidatuddannelse i Statskundskab"] <- 1

#Pernille Skipper
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Pernille Skipper (Enhedslisten)" & eksperiment_df$udd_egen_formand =="Kandidatuddannelse i Jura"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Pernille Skipper (Enhedslisten)" & eksperiment_df$udd_anden_formand =="Kandidatuddannelse i Jura"] <- 1

#Pia Olsen Dyhr
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Pia Olsen Dyhr (Socialistisk Folkeparti)" & eksperiment_df$udd_egen_formand =="Kandidatuddannelse i Statskundskab"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Pia Olsen Dyhr (Socialistisk Folkeparti)" & eksperiment_df$udd_anden_formand =="Kandidatuddannelse i Statskundskab"] <- 1

#Søren Pape
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Søren Pape Poulsen (Det Konservative Folkeparti)" & eksperiment_df$udd_egen_formand =="Skolelærer"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Søren Pape Poulsen (Det Konservative Folkeparti)" & eksperiment_df$udd_anden_formand =="Skolelærer"] <- 1

#Uffe Elbæk
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Uffe Elbæk (Alternativet)" & eksperiment_df$udd_egen_formand =="Socialpædagog"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Uffe Elbæk (Alternativet)" & eksperiment_df$udd_anden_formand =="Socialpædagog"] <- 1

#Klaus Riskjær
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Klaus Riskær Pedersen (Klaus Riskær Pedersen)" & eksperiment_df$udd_egen_formand =="Kandidatuddannelse i Erhvervsøkonomi"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Klaus Riskær Pedersen (Klaus Riskær Pedersen)" & eksperiment_df$udd_anden_formand =="Kandidatuddannelse i Erhvervsøkonomi"] <- 1

#Pernille Vermund
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Pernille Vermund (Nye Borgerlige)" & eksperiment_df$udd_egen_formand =="Arkitekt"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Pernille Vermund (Nye Borgerlige)" & eksperiment_df$udd_anden_formand =="Arkitekt"] <- 1

#Stig Grenov
eksperiment_df$formand_dik_udd[eksperiment_df$egen_formand =="Stig Grenov (Kristendemokraterne)" & eksperiment_df$udd_egen_formand =="Skolelærer"] <- 1
eksperiment_df$formand_dik_udd[eksperiment_df$anden_formand =="Stig Grenov (Kristendemokraterne)" & eksperiment_df$udd_anden_formand =="Skolelærer"] <- 1

#Resten
eksperiment_df$formand_dik_udd[is.na(eksperiment_df$egen_formand) == TRUE & is.na(eksperiment_df$anden_formand) == TRUE] <- NA
eksperiment_df$formand_dik_udd[eksperiment_df$udd_egen_formand =="Ved ikke"] <- NA
eksperiment_df$formand_dik_udd[eksperiment_df$udd_anden_formand =="Ved ikke"] <- NA
eksperiment_df$formand_dik_udd[eksperiment_df$formand_dik_udd == 99] <- 0
table(eksperiment_df$formand_dik_udd)
```

```{r logit-udd, fig.cap="Kendskab til partiformændenes uddannelse", echo=FALSE, include=FALSE}
# FORMÆNDENES UDDANNELSE SAMLET
#Først uden parti
sig_udd_logit<-glm(formula = as.numeric(formand_dik_udd) ~ as.factor(egen_formand_dik), 
                            family = binomial(link = "logit"), 
                            data = eksperiment_df)

#Så med parti
sig_udd_logit_parti<-glm(formula = as.numeric(formand_dik_udd) ~ as.factor(egen_formand_dik) + formand_set, 
                            family = binomial(link = "logit"), 
                            data = eksperiment_df)
```

```{r stargaz-udd, results='asis', message=F, warning=FALSE, echo=FALSE, eval=TRUE}
stargazer(sig_udd_logit, sig_udd_logit_parti, title="Kendskab til formændenes uddannelse", align=TRUE, type='latex',header=FALSE)
```

```{r ved-ikke-erhv-wrangling, echo=FALSE, include=FALSE}
#Laver variabel der viser, om man har svaret ved ikke (1) eller givet et bud (0)
eksperiment_df$ved_ikke_erhv <- 99
eksperiment_df$ved_ikke_erhv[eksperiment_df$erhv_egen_formand=="Ved ikke"] <- 1
eksperiment_df$ved_ikke_erhv[eksperiment_df$erhv_anden_formand=="Ved ikke"] <- 1

#Dem, som hverken har fået egen formand eller tilfældig anden formand gøres til NA
eksperiment_df$ved_ikke_erhv[is.na(eksperiment_df$erhv_egen_formand) == TRUE & is.na(eksperiment_df$erhv_anden_formand) == TRUE] <- NA

#De resterende, som ikke har svaret ved ikke og som ikke er NA, har angivet et bud og får værdien 0.
eksperiment_df$ved_ikke_erhv[eksperiment_df$ved_ikke_erhv==99] <- 0
table(eksperiment_df$ved_ikke_erhv)
```

```{r logit-ved-ikke-erhv, fig.cap="Kendskab til partiformændenes uddannelse", echo=FALSE, include=FALSE}
#Først uden parti
sig_ved_ikke_erhv_logit<-glm(formula = as.numeric(ved_ikke_erhv) ~ as.factor(egen_formand_dik), 
                            family = binomial(link = "logit"), 
                            data = eksperiment_df)

#Så med parti
sig_ved_ikke_erhv_logit_parti<-glm(formula = as.numeric(ved_ikke_erhv) ~ as.factor(egen_formand_dik) + formand_set, 
                            family = binomial(link = "logit"), 
                            data = eksperiment_df)

summary(sig_ved_ikke_erhv_logit)
summary(sig_ved_ikke_erhv_logit_parti)
```

```{r stargaz-ved-ikke-erhv, results='asis', message=F, warning=FALSE, echo=FALSE, eval=TRUE}
stargazer(sig_ved_ikke_erhv_logit, sig_ved_ikke_erhv_logit_parti, title="Ved ikke-andele for erhvervserfaring", align=TRUE, type='latex',header=FALSE)
```

```{r erhv-wrangling, include=FALSE, echo=FALSE}
#Undersøger variablene
unique(eksperiment_df$erhv_egen_formand)
unique(eksperiment_df$egen_formand)

table(eksperiment_df$erhv_egen_formand)
table(eksperiment_df$erhv_anden_formand)

#Koder dikotom variabel for, om respondenterne har gættet rigtigt på uddannelse
eksperiment_df$formand_dik_erhv <- 99
table(eksperiment_df$formand_dik_erhv)

#Anders Samuelsen
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Anders Samuelsen (Liberal Alliance)" & eksperiment_df$erhv_egen_formand =="2-4 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Anders Samuelsen (Liberal Alliance)" & eksperiment_df$erhv_anden_formand =="2-4 år"] <- 1

#Kristian Thulesen Dahl
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Kristian Thulesen Dahl (Dansk Folkeparti)" & eksperiment_df$erhv_egen_formand =="Under 2 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Kristian Thulesen Dahl (Dansk Folkeparti)" & eksperiment_df$erhv_anden_formand =="Under 2 år"] <- 1

#Lars Løkke Ramussen
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Lars Løkke Rasmussen (Venstre)" & eksperiment_df$erhv_egen_formand =="5-8 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Lars Løkke Rasmussen (Venstre)" & eksperiment_df$erhv_anden_formand =="5-8 år"] <- 1

#Mette Frederiksen
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Mette Frederiksen (Socialdemokratiet)" & eksperiment_df$erhv_egen_formand =="Under 2 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Mette Frederiksen (Socialdemokratiet)" & eksperiment_df$erhv_anden_formand =="Under 2 år"] <- 1

#Morten Østergaard
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Morten Østergaard (Radikale Venstre)" & eksperiment_df$erhv_egen_formand =="2-4 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Morten Østergaard (Radikale Venstre)" & eksperiment_df$erhv_anden_formand =="2-4 år"] <- 1

#Pernille Skipper
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Pernille Skipper (Enhedslisten)" & eksperiment_df$erhv_egen_formand =="Under 2 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Pernille Skipper (Enhedslisten)" & eksperiment_df$erhv_anden_formand =="Under 2 år"] <- 1

#Pia Olsen Dyhr
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Pia Olsen Dyhr (Socialistisk Folkeparti)" & eksperiment_df$erhv_egen_formand =="5-8 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Pia Olsen Dyhr (Socialistisk Folkeparti)" & eksperiment_df$erhv_anden_formand =="5-8 år"] <- 1

#Søren Pape
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Søren Pape Poulsen (Det Konservative Folkeparti)" & eksperiment_df$erhv_egen_formand =="Over 12 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Søren Pape Poulsen (Det Konservative Folkeparti)" & eksperiment_df$erhv_anden_formand =="Over 12 år"] <- 1

#Uffe Elbæk
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Uffe Elbæk (Alternativet)" & eksperiment_df$erhv_egen_formand =="Over 12 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Uffe Elbæk (Alternativet)" & eksperiment_df$erhv_anden_formand =="Over 12 år"] <- 1

# OBS: Hvordan ønsker vi at indsamle erhvervserfaring for partiformænd, som ikke sidder i folketinget?
eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Klaus Riskær Pedersen (Klaus Riskær Pedersen)"  & eksperiment_df$erhv_egen_formand =="Over 12 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Klaus Riskær Pedersen (Klaus Riskær Pedersen)" & eksperiment_df$erhv_anden_formand =="Over 12 år"] <- 1

eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Pernille Vermund (Nye Borgerlige)" & eksperiment_df$erhv_egen_formand =="Over 12 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Pernille Vermund (Nye Borgerlige)" & eksperiment_df$erhv_anden_formand =="Over 12 år"] <- 1

eksperiment_df$formand_dik_erhv[eksperiment_df$egen_formand =="Stig Grenov (Kristendemokraterne)" & eksperiment_df$erhv_egen_formand =="Over 12 år"] <- 1
eksperiment_df$formand_dik_erhv[eksperiment_df$anden_formand =="Stig Grenov (Kristendemokraterne)" & eksperiment_df$erhv_anden_formand =="Over 12 år"] <- 1

table(eksperiment_df$formand_dik_erhv)

#Resten
eksperiment_df$formand_dik_erhv[is.na(eksperiment_df$egen_formand) == TRUE & is.na(eksperiment_df$anden_formand) == TRUE] <- NA
eksperiment_df$formand_dik_erhv[eksperiment_df$erhv_egen_formand =="Ved ikke"] <- NA
eksperiment_df$formand_dik_erhv[eksperiment_df$erhv_anden_formand =="Ved ikke"] <- NA
eksperiment_df$formand_dik_erhv[eksperiment_df$formand_dik_erhv == 99] <- 0
table(eksperiment_df$formand_dik_erhv)
```

```{r logit-erhv, fig.cap="Kendskab til partiformændenes uddannelse", echo=FALSE, include=FALSE}
#Først uden parti
sig_erhv_logit<-glm(formula = as.numeric(formand_dik_erhv) ~ as.factor(egen_formand_dik), 
                            family = binomial(link = "logit"), 
                            data = eksperiment_df)

#Så med parti
sig_erhv_logit_parti<-glm(formula = as.numeric(formand_dik_erhv) ~ as.factor(egen_formand_dik) + formand_set, 
                            family = binomial(link = "logit"), 
                            data = eksperiment_df)

summary(sig_erhv_logit)
summary(sig_erhv_logit_parti)
```

```{r stargaz-erhv, results='asis', message=F, warning=FALSE, echo=FALSE, eval=TRUE}
stargazer(sig_erhv_logit, sig_erhv_logit_parti, title="Kendskab til formændenes erhvervserfaring", align=TRUE, type='latex',header=FALSE)
```

