---
header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage{booktabs} 
    - \usepackage{tabularx}
output:   
  bookdown::pdf_document2:
  fig_caption: true
  fontsize: 10.5pt
---

## Rensning af uddannelsedata fra Valgundersøgelsen (1971-2015)
Først indlæser og renser vi fil fra 1971-2005.
```{r, eval=FALSE}
d<-read.spss("...data", to.data.frame = T)

# Vælger de relevante variable og fjerner ikke-spurgt / uoplyst
d1<- d %>%
  select(year, weight, eduown) %>%
  filter(eduown!="Nægter at svare"&eduown!="Ikke spurgt"&eduown!="Uoplyst")

#### SKOLEUDDANNELSE
## Eduown gælder i 1971 og 1977 til 2005
df<-as_tibble(as.data.frame(prop.table(table(d1$eduown, d1$year), 2))) %>% 
  filter(Var1=="Studentereksamen (12+ år)") %>%
  mutate(year=Var2, 
        andel_boglig=Freq,
        gruppe="Valgundersøgelsen") %>%
  select(year, andel_boglig, gruppe)

df$year<-as.numeric(as.character(df$year))
```

Herefter indlæser og renser vi fil fra valgårene 2007, 2011 og 2015.
```{r, eval=FALSE}
# Valåret 2007
d_07 <- read.dta("...data")

d_07_kodet <- d_07 %>%
  filter(v432!="Don't know"&v432!="Other")

d07<-as_tibble(as.data.frame(prop.table(table(d_07_kodet$v432)))) %>%
  mutate(student = str_detect(Var1, "Upper|Higher")) %>%
  group_by(student) %>%
  summarise(andel_boglig=sum(Freq)) %>%
  ungroup() %>%
  filter(student==T) %>%
  mutate(year=2007, 
         gruppe="Valgundersøgelsen") %>%
  select(-student)

# Valgåret 2011
d_11 <- read.dta("...data")

d_11_kodet <- d_11 %>%
  filter(v327!="Under school education"&v327!="Other")

d11<-as_tibble(as.data.frame(prop.table(table(d_11_kodet$v327)))) %>%
  mutate(student = str_detect(Var1, "Upper|Higher")) %>%
  group_by(student) %>%
  summarise(andel_boglig=sum(Freq)) %>%
  ungroup() %>%
  filter(student==T) %>%
  mutate(year=2011, 
         gruppe="Valgundersøgelsen") %>%
  select(-student)

# Valgåret 2015 
gruppe <- "Valgundersøgelsen"
year<- 2015
andel_boglig<- 0.528

d15<-data.frame(gruppe, year, andel_boglig)
```

Vi kombinerer de forskellige datasæt og klargør til figur
```{r, eval=FALSE}
#Bind rækker
df_ValUnd<-full_join(df,d07) %>%
  full_join(d11) %>%
  full_join(d15)

## Vi laver upper og lower boundary
d1_n<-d1 %>%
  group_by(year) %>%
  count()

n<-c(nrow(d_07_kodet), nrow(d_11_kodet), 2001)
year<-c(2007,2011,2015)

d07_15n <- data.frame(n, year)

n_data<-full_join(d1_n, d07_15n)

#Sætter n på
df_ValUnd<-left_join(df_ValUnd, n_data, by="year")

# Udregner usikkerhed
df_ValUnd$std_error<- sqrt(df_ValUnd$andel_boglig * (1 - df_ValUnd$andel_boglig)  / df_ValUnd$n )
df_ValUnd$ub95<-df_ValUnd$andel_boglig + 1.96*df_ValUnd$std_error
df_ValUnd$lb95<-df_ValUnd$andel_boglig - 1.96*df_ValUnd$std_error
```
