---
header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage{booktabs} 
    - \usepackage{tabularx}
output:   
  bookdown::pdf_document2:
  fig_caption: true
  fontsize: 10.5pt
---

# Bilag 6: Diskussion
```{r Load-pakker, include=FALSE}
library(cregg)
library(dplyr) # Kan wrangle data
library(tidyr) # Kan wrangle data
library(forcats) # Til at arbejde med kategorisk data
library(stringr)
library(ggplot2)
library(ggpubr) #Flere plots på samme side
```


### Kendskab til Folketingets sammensætning
Vi undersøger vælgernes kendskab til folketingets sammensætning på lang videregående uddannelse og erhvervserfaring.
```{r andel-kender-udd-FT-app, echo=FALSE, include=FALSE}
#Respondenternes estimat: Gennemsnit 37.291 der har en lang videregående uddannelse. Respondenterne underestimerer altså andelens med lang videregående uddannelse.
eksperiment_df<-readRDS(file="/Users/annesofieevert/Google_Drive_evert.klint.2019@gmail.com/04_Data/02_Estimation/02_Data/eksperiment_df_clean.Rds")


mean(eksperiment_df$est_lang_udd)

udd_FT_plot <-  ggplot(eksperiment_df) +
    geom_density( aes(est_lang_udd, stat(count)), alpha=0.7, fill="gray80") +
    geom_vline(xintercept =c(44.571429), col = "#440154FF") + #Reelle gennemsnit
    ggplot2::annotate("text", 
                      x =c(55), y=17,
                      label="44,57 %", col="#440154FF") +
    #geom_vline(xintercept =c(37.291), col = "#FDE725FF") + #Respondenternes gennemsnit
    #ggplot2::annotate("text", 
    #                  x =c(28), y=17,
    #                  label="37,29 %", col="#FDE725FF") +
  theme_classic()+
  ylab("Antal respondenter") +
  xlab("Andel MF'ere med lang vidr. udd.") +
  ggtitle("A")+
  theme(legend.position="none")

prop.table(table(eksperiment_df$est_lang_udd<44.57))
```
